# Generated by Django 4.2.10 on 2025-03-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_type", models.CharField(max_length=50)),
                ("instrument", models.CharField(max_length=50)),
                ("target", models.CharField(max_length=50)),
                ("horizon", models.IntegerField()),
                ("training_period", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("trained", "Trained"),
                            ("failed", "Failed"),
                        ],
                        default="training",
                        max_length=10,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
