# Generated by Django 4.2.10 on 2025-03-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0002_mlmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodel",
            name="training_phase",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
