# Generated by Django 4.2.10 on 2025-03-18 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0003_mlmodel_training_phase_alter_mlmodel_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell"), ("hold", "Hold")],
                        max_length=10,
                    ),
                ),
                ("confidence", models.FloatField()),
                ("reason", models.TextField()),
                ("timeframe", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="market_data.mlmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelPredictionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("actual_value", models.FloatField()),
                ("predicted_value", models.FloatField()),
                ("error", models.FloatField()),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction_history",
                        to="market_data.mlmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="ModelFeatureImportance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_name", models.CharField(max_length=100)),
                ("importance_value", models.FloatField()),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_importance",
                        to="market_data.mlmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelAccuracyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("accuracy", models.FloatField()),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accuracy_history",
                        to="market_data.mlmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
