# Generated by Django 4.2.10 on 2025-03-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0004_tradingrecommendation_modelpredictionhistory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlmodel",
            name="training_phase",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="modelpredictionhistory",
            name="error",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
