# Generated by Django 4.2.10 on 2025-03-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0005_alter_mlmodel_training_phase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodel",
            name="last_retrained",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("training", "Training"),
                    ("trained", "Trained"),
                    ("active", "Active"),
                    ("queued_for_retraining", "Queued for Retraining"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
    ]
