apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama
          ports:
            - containerPort: 11434
          env:
            - name: no_proxy
              value: "${no_proxy}"
            - name: http_proxy
              value: "${http_proxy}"
            - name: https_proxy
              value: "${https_proxy}"
            - name: LLM_MODEL_ID
              value: "${LLM_MODEL_ID}"
            - name: host_ip
              value: "${host_ip}"
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  type: NodePort
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 11434
      nodePort: 30008