# Generated by Django 5.0.2 on 2025-02-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_studyactivity_alter_group_id_alter_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='english',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='spanish',
            field=models.CharField(max_length=100),
        ),
    ]
